### ISSUE TITLE
'NoneType' object has no attribute 'parent'

### ISSUE THREAD

**Issue by mtvx** [davidism/sphinxcontrib-log-cabinet#3]
Building (werkzeug) docs on `3.6` fails into: 

```
Traceback (most recent call last):
  File "/home/musttu/.pyenv/versions/3.6.4/envs/werkzeug3/lib/python3.6/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/home/musttu/.pyenv/versions/3.6.4/envs/werkzeug3/lib/python3.6/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/home/musttu/.pyenv/versions/3.6.4/envs/werkzeug3/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 338, in build_update
    'out of date' % len(to_build))
  File "/home/musttu/.pyenv/versions/3.6.4/envs/werkzeug3/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 399, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/musttu/.pyenv/versions/3.6.4/envs/werkzeug3/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 436, in write
    self._write_serial(sorted(docnames))
  File "/home/musttu/.pyenv/versions/3.6.4/envs/werkzeug3/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 443, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/home/musttu/.pyenv/versions/3.6.4/envs/werkzeug3/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 813, in get_and_resolve_doctree
    self.apply_post_transforms(doctree, docname)
  File "/home/musttu/.pyenv/versions/3.6.4/envs/werkzeug3/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 865, in apply_post_transforms
    self.app.emit('doctree-resolved', doctree, docname)
  File "/home/musttu/.pyenv/versions/3.6.4/envs/werkzeug3/lib/python3.6/site-packages/sphinx/application.py", line 444, in emit
    return self.events.emit(event, self, *args)
  File "/home/musttu/.pyenv/versions/3.6.4/envs/werkzeug3/lib/python3.6/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/home/musttu/.pyenv/versions/3.6.4/envs/werkzeug3/lib/python3.6/site-packages/sphinxcontrib/log_cabinet.py", line 35, in handle_doctree_resolved
    del after.parent[index:index + len(log)]
AttributeError: 'NoneType' object has no attribute 'parent'
```

Same on `3.4` (didn't test other 3.x versions).

**Comment by mtvx** [comment]
This isn't probably version but content dependent - certain content (or lack of it) in a docstring produces it.
