### ISSUE TITLE
super() argument 1 must be type, not classobj

### ISSUE THREAD

**Issue by audstanley** [davidism/sphinxcontrib-log-cabinet#4]
Got this error, maybe you could help shed some light on what this means?  A syntax change in python, maybe?  Thank you.
```
STANLEY => docs ⛰  >>> python --version
Python 2.7.15rc1
STANLEY => docs ⛰  >>> make epub
Running Sphinx v1.8.3
loading intersphinx inventory from https://docs.sqlalchemy.org/objects.inv...
intersphinx inventory has moved: https://docs.sqlalchemy.org/objects.inv -> https://docs.sqlalchemy.org/en/latest/objects.inv
loading intersphinx inventory from https://pythonhosted.org/blinker/objects.inv...
loading intersphinx inventory from http://jinja.pocoo.org/docs/objects.inv...
loading intersphinx inventory from http://werkzeug.pocoo.org/docs/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://itsdangerous.palletsprojects.com/objects.inv...
intersphinx inventory has moved: https://itsdangerous.palletsprojects.com/objects.inv -> https://itsdangerous.palletsprojects.com/en/1.1.x/objects.inv
loading intersphinx inventory from https://click.palletsprojects.com/objects.inv...
intersphinx inventory has moved: https://click.palletsprojects.com/objects.inv -> https://click.palletsprojects.com/en/7.x/objects.inv
loading intersphinx inventory from https://wtforms.readthedocs.io/en/stable/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [epub]: targets for 79 source files that are out of date
updating environment: 79 added, 0 changed, 0 removed
reading sources... [100%] views
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  1%] advanced_foreword
Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/log_cabinet.py", line 62, in __init__
    super(ChangelogVisitor, self).__init__(document)
TypeError: super() argument 1 must be type, not classobj
The full traceback has been saved in /tmp/sphinx-err-OmSGgn.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:20: recipe for target 'epub' failed
make: *** [epub] Error 2
```

**Comment by audstanley** [comment]
Here is the full traceback error log output:
I'm just trying to build either the html or epub output for flask for a class I'm taking.
```
# Sphinx version: 1.8.3
# Python version: 2.7.15rc1 (CPython)
# Docutils version: 0.14
# Jinja2 version: 2.10
# Last messages:
#
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [  1%] advanced_foreword
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.3) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/mathjax.pyc
#   alabaster (0.7.12) from /usr/local/lib/python2.7/dist-packages/alabaster/__init__.pyc
#   sphinx.ext.autodoc (1.8.3) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc/__init__.pyc
#   sphinx.ext.intersphinx (1.8.3) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/intersphinx.pyc
#   pallets_sphinx_themes (1.1.2) from /usr/local/lib/python2.7/dist-packages/pallets_sphinx_themes/__init__.pyc
#   sphinxcontrib.log_cabinet (1.0.0) from /usr/local/lib/python2.7/dist-packages/sphinxcontrib/log_cabinet.pyc
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 412, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 593, in write
    self._write_serial(sorted(docnames))
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 601, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment/__init__.py", line 627, in get_and_resolve_doctree
    self.apply_post_transforms(doctree, docname)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment/__init__.py", line 679, in apply_post_transforms
    self.app.emit('doctree-resolved', doctree, docname)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 510, in emit
    return self.events.emit(event, self, *args)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/events.py", line 80, in emit
    results.append(callback(*args))
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/log_cabinet.py", line 28, in handle_doctree_resolved
    visitor = ChangelogVisitor(doctree, app)
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/log_cabinet.py", line 62, in __init__
    super(ChangelogVisitor, self).__init__(document)
TypeError: super() argument 1 must be type, not classobj
```

**Comment by audstanley** [comment]
I just found the issue here:
https://github.com/davidism/sphinxcontrib-log-cabinet/issues/2
closing.
